version: "3.8"

services:

  eureka-server:
    build: ./eurika
    ports:
      - "8761:8761"
    environment:
      - SPRING_APPLICATION_NAME=eureka-service
    networks:
      - biblio-network

  gateway-service:
    build: ./gateway
    ports:
      - "9999:9999"
    depends_on:
      - eureka-server
    environment:
      - SPRING_APPLICATION_NAME=gateway-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - biblio-network

  user-service:
    build: ./user
    depends_on:
      - eureka-server
    environment:
      - SPRING_APPLICATION_NAME=user-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - biblio-network

  book-service:
    build: ./book
    depends_on:
      - eureka-server
    environment:
      - SPRING_APPLICATION_NAME=book-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - biblio-network

  emprunt-service:
    build: ./emprunter
    depends_on:
      - eureka-server
      - user-service
      - book-service
    environment:
      - SPRING_APPLICATION_NAME=emprunt-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - biblio-network

networks:
  biblio-network:
    driver: bridge
