version: "3.8"

services:

  eureka-server:
    build: ./eurika
    ports:
      - "8761:8761"
    environment:
      - SPRING_APPLICATION_NAME=eureka-service
    networks:
      - biblio-network

  gateway-service:
    build: ./gateway
    ports:
      - "9999:8080"
    depends_on:
      - eureka-server
    environment:
      - SPRING_APPLICATION_NAME=gateway-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - biblio-network
  notification-service:
    build: ./notification
    container_name: notification-service
    depends_on:
      - eureka-server
      - kafka
    environment:
      - SPRING_APPLICATION_NAME=notification-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - biblio-network

  mysql-user:
    image: mysql:8
    container_name: mysql-user
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_user
    ports:
      - "3307:3306"
    networks:
      - biblio-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  mysql-book:
    image: mysql:8
    container_name: mysql-book
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_book
    ports:
      - "3308:3306"
    networks:
      - biblio-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  mysql-emprunt:
    image: mysql:8
    container_name: mysql-emprunt
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_emprunter
    ports:
      - "3309:3306"
    networks:
      - biblio-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  user-service:
    build: ./user
    depends_on:
      mysql-user:
        condition: service_healthy
    environment:
      - SPRING_APPLICATION_NAME=user-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - biblio-network
    restart: on-failure

  book-service:
    build: ./book
    depends_on:
      mysql-book:
        condition: service_healthy
    environment:
      - SPRING_APPLICATION_NAME=book-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - biblio-network
    restart: on-failure

  emprunt-service:
    build: ./emprunter
    depends_on:
      mysql-emprunt:
        condition: service_healthy
    environment:
      - SPRING_APPLICATION_NAME=emprunt-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - biblio-network
    restart: on-failure

  zookeeper:
    image: confluentinc/cp-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - biblio-network

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - biblio-network

networks:
  biblio-network:
    driver: bridge